### PR TITLE
Fix typo in cpp.cpp

### PR DESCRIPTION
**Pull request by georgimkv**
This change substitutes line 4:
whi**t**e(1)
for
whi**l**e(1)

### CODE REVIEW

**Review by iamtraction — APPROVED** [review]
Thanks! I didn't see that typo until now. 👌

**Comment by georgimkv** [comment]
Hi. I just noticed the same typo is on c.c as well

**Comment by iamtraction** [comment]
The `.cpp` file is just a copy of the `.c` file. Since C code will work with C++. So would you like to open a PR for that?

**Comment by georgimkv** [comment]
Right. I'll open another one and you may merge it if you wish.

**Pull request merged**
